### ISSUE TITLE
获取图标库在线链接失败(iconfont更新在线链接或不支持)

### ISSUE THREAD

**Issue by tonny3548** [gaoxiaosi/iconfont-manager#1]
iconfont-manager初始化后在"开始获取图标库在线链接"报错
const timeoutError = new Errors_js_1.TimeoutError(`waiting for ${options.title} failed: timeout ${options.timeout}ms exceeded`);
可能需要更新了,而且目前iconfont网站处于维护状态,可以添加仅支持下载使用的功能,不需要一定支持在线链接

**Comment by gaoxiaosi** [comment]
感谢反馈！不只是在线链接的功能受限，还有一些DOM元素也有变化，而且网站还不稳定。本来想着等iconfont网站恢复再一起处理，但好多天了一直没有恢复。。
最新的1.9.0版本，暂时关闭了在线链接的功能，其他初始化、脚本下载图标库、图形化操作的功能应该可以正常体验。

**Comment by gaoxiaosi** [comment]
> 感谢反馈！不只是在线链接的功能受限，还有一些DOM元素也有变化，而且网站还不稳定。本来想着等iconfont网站恢复再一起处理，但好多天了一直没有恢复。。
> 最新的1.9.0版本，暂时关闭了在线链接的功能，其他初始化、脚本下载图标库、图形化操作的功能应该可以正常体验。

感谢反馈！不只是在线链接的功能受限，还有一些DOM元素也有变化，而且网站还不稳定。本来想着等iconfont网站恢复再一起处理，但好多天了一直没有恢复。。
最新的1.9.0版本，暂时关闭了在线链接的功能，其他初始化、脚本下载图标库、图形化操作的功能应该可以正常体验。

**Comment by gaoxiaosi** [comment]
> iconfont-manager初始化后在"开始获取图标库在线链接"报错 const timeoutError = new Errors_js_1.TimeoutError(`waiting for ${options.title} failed: timeout ${options.timeout}ms exceeded`); 可能需要更新了,而且目前iconfont网站处于维护状态,可以添加仅支持下载使用的功能,不需要一定支持在线链接

感谢反馈！不只是在线链接的功能受限，还有一些DOM元素也有变化，而且网站还不稳定。本来想着等iconfont网站恢复再一起处理，但好多天了一直没有恢复。。
最新的1.9.0版本，暂时关闭了在线链接的功能，其他初始化、脚本下载图标库、图形化操作的功能应该可以正常体验。
